FIXED: #160 (Enhanced the Post-Registration UI Page)
Note-Vault/Note-Vault pull request #219
Opened 2024-05-19 19:25 UTC by AkshitGarg24

Fixes #160 

The changes have been made to the Post-Registration Page. Please see the attached image below.

![Image](https://github.com/Note-Vault/Note-Vault/assets/153659573/6da4abd5-39a5-4d3d-bfa6-2f4b36b5c771)

2024-05-20 02:49 UTC, VaibhavArora314 requested changes
do not push changes to .env.example

2024-05-20 04:51 UTC, goyalh4164 approved these changes

2024-05-20 12:50 UTC, Ultimateutkarsh11 commented
Resolve the merge conflicts in the following:
public/style/style.css

2024-05-20 13:35 UTC, merged

2024-05-30 12:03 UTC, AkshitGarg24 commented
@VaibhavArora314 @Ultimateutkarsh11 @goyalh4164 Anyone please add my name in the Assignees Section.