about link added
Note-Vault/Note-Vault pull request #238
Opened 2024-05-21 14:23 UTC by harinisayani

I have added about link in navbar.

https://github.com/Note-Vault/Note-Vault/assets/143276011/c63d4970-4580-4881-8053-fa34086a1472

2024-05-22 10:30 UTC, Ultimateutkarsh11 requested changes
@harinisayani kindly resolve the merge conflicts

2024-05-22 10:45 UTC, harinisayani commented
Hi @Ultimateutkarsh11,
I have resolved all the conflicts.

2024-05-22 16:40 UTC, VaibhavArora314 approved these changes

2024-05-23 07:44 UTC, Ultimateutkarsh11 approved these changes

2024-05-23 10:10 UTC, goyalh4164 approved these changes

2024-05-23 10:10 UTC, merged

2024-05-23 12:19 UTC, harinisayani commented
Hi @goyalh4164 
Could you please add GSSOC and level label