Feat: Adding new feature for organization of notes category wise
Note-Vault/Note-Vault pull request #257
Opened 2024-05-23 08:50 UTC by Chelseasingla1

i added new feature where one can chose or organize their notes according to category 

![image](https://github.com/Note-Vault/Note-Vault/assets/129886894/41409e5d-24aa-4776-960b-c7bd91966fc6)

Database is also getting updated:
![image](https://github.com/Note-Vault/Note-Vault/assets/129886894/d4e355b3-21fe-4755-88bf-9228913cd6cc)

Demo Video:
https://youtu.be/KilM1KnTGaI

This issue is under #24

2024-05-23 11:43 UTC, VaibhavArora314 approved these changes

2024-05-24 07:12 UTC, goyalh4164 commented
@Chelseasingla1 your branch has merge conflicts

2024-05-24 07:16 UTC, Chelseasingla1 commented
> @Chelseasingla1 your branch has merge conflicts

what conflicts

2024-05-24 13:17 UTC, Ultimateutkarsh11 requested changes
@Chelseasingla1 resolve the merge conflicts in the following:
controllers/notebook.js
model/Notebook.js

2024-05-27 14:49 UTC, closed without merging